feat: ZNSPriceOracle
zer0-os/ZNS pull request #11
Opened 2023-04-10 20:50 UTC by JamesEarle

The ZNSPriceOracle contract allows ZNS to get the price of a domain based on the length of that domain. Two different base fees exist, one for root domains and one for subdomains. We call this the `basePrice`

Some amount of domains that are less than a certain length will all be the same, we call this a `baseLength`

There also exists a price multiplier we can use to modify how steep the price drop is in domain names from the initial base price. By default, this value is `3.9` because it forms a reasonable price decline.

We use a simple formula to calculate a domain's price: `(priceMultiplier * basePrice) / length`

Because no decimal values exist in Solidity, we increase by an order of 10 when storing the value for the multiplier and decrease by the same amount in the call to get a domain's price.

This is a visual of the curve of prices with a default `baseLength` of 3

![image](https://user-images.githubusercontent.com/5976499/230996259-b425fcaf-8441-45c2-bc3a-c0a7e7ba72c4.png)

2023-04-10 22:53 UTC, RyanCross commented on contracts/ZNSPriceOracle.sol
> +  function setBaseLength(uint8 length) external onlyAuthorized {
what's the context of this requirement? What happens if a root domain's name >= then 5? (5 character limit on domain name seems pretty restrictive)

EDIT: I think the meat of what I'm trying to figure out here is: will the root domain always be "zero" in this new architecture?

2023-04-10 23:23 UTC, Whytecrowe commented on contracts/ZNSPriceOracle.sol
> +  function setBaseLength(uint8 length) external onlyAuthorized {
I think we've confused outselves with the terms Neo uses. He calls 2LDs root domains, which means, it's the first level domain after `0://`, which is what we used for naming here (let me know if it's confusing and we should change it).
in reality, of course, they are not roots in the conventional sense. they are 2LDs (e.g. `0://wilder`).
There's not limit for the length other then Solidity's limit of 255, I think.

Not sure what you mean by "always be "zero"".
The base price is set to all domains lower then "base length", meaning that price after string length of 5 chars will be dropping asymptotically, before 5 chars the price is fixed and maximal.

Did I understand your question right? :)

2023-04-10 23:55 UTC, Whytecrowe commented on contracts/IZNSPriceOracle.sol
> +  event BaseLengthSet(uint8 length);
please, add all externally called functions to this interface to make it an actual interface

2023-04-10 23:58 UTC, Whytecrowe commented on contracts/ZNSPriceOracle.sol
> +   * a reasonable decline in pricing visually when graphed.
change this for a TODO comment if it's personal thoughts that need to be addressed later. natspec should be facing the user or a developer that builds on top of the current module.
I like the comment, just don't want us to miss it :)

2023-04-10 23:59 UTC, Whytecrowe commented on contracts/ZNSPriceOracle.sol
> +  uint public priceMultiplier = 39;
this shouldn't have a value in the code. should only be a settable var, that we initialize at construction time.
same for the one below (`baseLength`). should be set in constructor/init

2023-04-11 00:00 UTC, Whytecrowe commented on contracts/ZNSPriceOracle.sol
> +  mapping(address => bool) authorized;
please add a TODO comment with words "access control" in it. there will be a larger task of setting proper access control for the whole system. this should be a part of it. TODO comments will help mark the spots where AC needs to be evaluated.

2023-04-11 00:01 UTC, Whytecrowe commented on contracts/ZNSPriceOracle.sol
> +    address znsRegistrar_
add `baseLength` and `priceMultiplier`

2023-04-11 00:02 UTC, Whytecrowe commented on contracts/ZNSPriceOracle.sol
> +   * @param isRootDomain Flag for which base price to use. True for subdomain, false for root.
wrong comment. should be "true" for root domains

2023-04-11 00:06 UTC, Whytecrowe commented on contracts/ZNSPriceOracle.sol
> +    return (priceMultiplier * basePrice) / length / 10;
do we have any edges for this formula? any values for which this formula breaks or we get non integer values? should we add some kind of check for these values?

2023-04-11 00:07 UTC, Whytecrowe commented on contracts/ZNSPriceOracle.sol
> +    znsRegistrar = znsRegistrar_;
check zero address before setting

2023-04-11 00:12 UTC, Whytecrowe commented on test/ZNSPriceOracle.test.ts
> +      const expectedPrice = (defaultRootPrice.mul(defaultMultiplier)).div(domain.length).div(10);
DRY
this can be extracted into a function and reused across all tests instead of copying. we will need this function later for other things and tests.

2023-04-11 00:19 UTC, Whytecrowe commented on test/ZNSPriceOracle.test.ts
> +      const newBasePrice = hre.ethers.utils.parseEther("0.7");
just a tiny nit:
if we destructure needed methods in imports, we can just type `par...` and it will autocomplete to the method we need.
this is instead of typing the whole access chain here `hre.ethers.utils...` or looking for it's usages to copy and paste. time-saving, but also a personal preference...

2023-04-11 00:25 UTC, Whytecrowe commented on test/ZNSPriceOracle.test.ts
> +    it("Allows setting the multiplier to zero", async () => {
Just writing thoughts here...
Setting multiplier to 0 will make all domains <= `baseLength` to be priced with `basePrice`, but everything after that will be zero.
We can use this to change pricing models by e.g. making a fixed price for all domains under a certain limit and all longer domains be free.

2023-04-11 00:27 UTC, Whytecrowe commented on test/ZNSPriceOracle.test.ts
> +    it("Disallows an unauthorized user to set the base price", async () => {
"length"

2023-04-11 00:28 UTC, Whytecrowe commented on test/ZNSPriceOracle.test.ts
> +    it("Allows setting the boundary to zero", async () => {
this will make all prices 0. do we want there to be another way of doing this, besides changing the `basePrice`?
Maybe not to avoid mistakes?..

2023-04-11 00:31 UTC, Whytecrowe commented on contracts/ZNSPriceOracle.sol
> +  address public znsRegistrar;
missing a setter function for this

2023-04-11 00:38 UTC, Whytecrowe requested changes
Nice clean pretty code! :)
Some minor comments to review.
Please, make sure you run `eslint` with `--fix` flag so it does a bit of reformatting.
Also, make sure you connect eslint locally in your IDE so it highlights errors as you type and also add `eslint --fix` to `actions on save`. Prettier can be turned off for now. We may add it later if needed.

Update this branch from `development`. A new PR has been merged.

2023-04-11 13:30 UTC, JamesEarle commented on contracts/ZNSPriceOracle.sol
> +   * a reasonable decline in pricing visually when graphed.
I like it there too, and agree it shouldn't be natspec I guess in that perspective, but also leaving it as TODO makes it feel like an action item that needs resolution, when it's really just explanatory. What do you think? Probably no tag is the best choice IMO

2023-04-11 13:31 UTC, JamesEarle commented on contracts/ZNSPriceOracle.sol
> +  uint public priceMultiplier = 39;
An effort to reduce the initializer params, they still have setters, but I can update them

2023-04-11 13:36 UTC, JamesEarle commented on contracts/ZNSPriceOracle.sol
> +   * @param isRootDomain Flag for which base price to use. True for subdomain, false for root.
I had the opposite logic at first and reversed it, forgot to also update the comment 👍

2023-04-11 13:40 UTC, JamesEarle commented on test/ZNSPriceOracle.test.ts
> +    it("Allows setting the multiplier to zero", async () => {
Correct yeah, we could extend the `baseLength` value so all domains that are 5 or 7 characters cost `basePrice` and the rest are free

2023-04-11 13:43 UTC, JamesEarle commented on test/ZNSPriceOracle.test.ts
> +    it("Allows setting the boundary to zero", async () => {
If either of the `basePrice` or `priceMultiplier` values are 0, then all domains are free that are above the specified length. If the length is 0 as well, then all domains are free, but if the length is 0 and the prior is not true (i.e. neither `basePrce` or `priceMultiplier` are 0) then we just perform the formula for their price based on the length, we don't return the base price

So it will only make all prices 0 in the case that at least one of `basePrce` or `priceMultiplier` is also 0

2023-04-11 15:41 UTC, JamesEarle commented on contracts/ZNSPriceOracle.sol
> +  function setBaseLength(uint8 length) external onlyAuthorized {
@RyanCross A top level domain like `0://wilder` will always have a `parentId` of `0x0...`, so the "root" will always be zero

2023-04-11 16:29 UTC, beardhero commented on contracts/ZNSPriceOracle.sol
> +    if (length == 0) return 0;
Is there a danger here of some external contract or app thinking that a length 0 domain is free and creating it?

I know we're preventing 0 from being set in other contacts, but if some future contract didn't then this might get missed?

Could just revert here instead

2023-04-11 16:32 UTC, JamesEarle commented on contracts/ZNSPriceOracle.sol
> +    return (priceMultiplier * basePrice) / length / 10;
@Whytecrowe If `priceMultiplier` or `basePrice` are 0, then this calculation returns 0. This calculation only gets performed if a domain name is longer than the `baseLength` value currently set. 

If `baseLength` is 0, then this function is always executed. In the case that `baseLength` and one or both of `priceMultplier` or `basePrice` are zero, this will return 0.

From our discussions, this may end up being a useful way to play with the pricing dynamic.

The only way this truly "breaks" is if `length` is zero, which is checked in the above external `getPrice` function

2023-04-11 16:40 UTC, JamesEarle commented on contracts/ZNSPriceOracle.sol
> +    if (length == 0) return 0;
Good question, I'm not sure. I didn't want to revert here as this is just a `view` function. I interpret this as more "there is no price for a 0 length domain" not "0 length domains are free".

I imagine when we have the Registrar call `registerDomain` or something similar, it would `require(length != 0)` there, before calling this, and it makes more sense to revert there, IMO

2023-04-11 16:42 UTC, beardhero commented on contracts/ZNSPriceOracle.sol
> +
So it's seems that with this contract, the intention is to deploy a new price oracle for every registrar. 

So what is this distinction between root and sub domains then?

The registrar, which should already be deployed and associated to a domain, should not need to set any prices for its root domains that are already minted.

2023-04-11 16:45 UTC, beardhero commented on contracts/ZNSPriceOracle.sol
> +    authorized[znsRegistrar_] = true;
So with this access pattern, a new price oracle has to be deployed for every new registrar?

Then shouldn't this oracle contract just get inherited by the registrars. They will at least have to import them to get setter access.

This means that the oracle needs the registrar to initialize and the registrar needs the oracle to initialize, which is a problem right?

2023-04-11 16:49 UTC, beardhero commented on contracts/ZNSPriceOracle.sol
> +    // higher than it is meant to be, so we divide by 10 to reverse that action.
Instead of magic number 10, set a constant priceDivisor and consider automatically setting it to a factor of the priceMultiplier when that's set.

2023-04-11 16:52 UTC, beardhero commented on contracts/ZNSPriceOracle.sol
> +    priceMultiplier = multiplier;
This can break the price calc if set too low.

Prevent setting 0 and <baseLength*priceDivisor

2023-04-11 16:58 UTC, beardhero commented on contracts/ZNSPriceOracle.sol
> +    }
Can break price calc if set too low

Prevent setting 0 and something like <baseLength*priceDivisor

2023-04-11 17:46 UTC, JamesEarle commented on contracts/ZNSPriceOracle.sol
> +    // higher than it is meant to be, so we divide by 10 to reverse that action.
@beardhero We always implicitly have to multiply by 10 to store the value we actually want, because we cant use fractional values like float or double, and so we have to always divide by 10 as well so this value is intentionally not variable.

2023-04-11 17:47 UTC, JamesEarle commented on contracts/ZNSPriceOracle.sol
> +
Resolving based on discussion in standup, the price oracle will be used only by our registrar

2023-04-11 17:48 UTC, JamesEarle commented on contracts/ZNSPriceOracle.sol
> +    authorized[znsRegistrar_] = true;
Per our conversation in standup, the price oracle will only be used by our main registrar

2023-04-11 17:53 UTC, JamesEarle commented on contracts/ZNSPriceOracle.sol
> +    }
From conversation with Kirill, the calc is meant to be able to return 0 in case we want to play with the way pricing works in any way like offering free domains for early adopters etc.

2023-04-11 18:03 UTC, Whytecrowe commented on contracts/ZNSPriceOracle.sol
> +    if (length == 0) return 0;
Even if Registrar does not check for 0, how would a zero length name even exist in the system? How would they access it?
So, they do create a free no name domain. what's next? can they actually use it?

2023-04-11 18:06 UTC, Whytecrowe commented on contracts/ZNSPriceOracle.sol
> +    authorized[znsRegistrar_] = true;
Not every Registrar has to have an Oracle. If someone wants to do it this complicated way - they have the right, but they are not obligated. they can handle the prices in whichever way they want.

Regarding initialization, I don't see it as a problem, we can set this as a part of our deployment process to initialize for one contract and then just use a setter for another one. Am I missing something here?

2023-04-11 18:07 UTC, Whytecrowe commented on contracts/ZNSPriceOracle.sol
> +    // higher than it is meant to be, so we divide by 10 to reverse that action.
I don't see why. the divisor here is to eliminate potential problems with decimals, right @JamesEarle ?
Why is it 10 and not a higher number like 1000? is one decimal enough for us to eliminate fractions? it doesn't seem like it's the case

2023-04-11 18:11 UTC, Whytecrowe commented on contracts/ZNSPriceOracle.sol
> +    priceMultiplier = multiplier;
maybe not 0, though. setting this to zero will allow us to eliminate prices for all domains after `baseLength`, which might be helpful, but I don't see when and why yet... either way, it's not "breaking" anything per se...
we do NOT want to have a 0, however, if we do set `priceMultiplier` as non-zero. hence my previous comments on what is the range of our actual valid values we can set here?..

2023-04-11 19:36 UTC, JamesEarle commented on contracts/ZNSPriceOracle.sol
> +    // higher than it is meant to be, so we divide by 10 to reverse that action.
@Whytecrowe This isn't for truncating to avoid fractional values, this is just for storing the multiplier. We *technically* can use any value for as many decimals of precision we want to store. If we want a multiplier to be something more precise, we can use 100,000 instead of 10, we just have to divide by the same number here when we call to getPrice.

I can just make it a variable if we want it to be adjustable, but I only see value in changes that either increase or decrese the amount of precision kept (e.g. 100 => 1000, not 100 => 150)

2023-04-13 18:26 UTC, beardhero commented on contracts/ZNSPriceOracle.sol
> +  function setBaseLength(uint8 length) external onlyAuthorized {
To keep the namehash process consistent, I think the root should be namehash("0://") instead of just 0. 
This makes it clear how we would deploy a new root.

2023-04-13 18:41 UTC, beardhero commented on contracts/ZNSPriceOracle.sol
> +    // higher than it is meant to be, so we divide by 10 to reverse that action.
I see what you mean that you're just trying to set the effective multiplier to 3.9, but also we have to be aware of the fraction truncation and dust - otherwise you would just set the price multiplier lower and save gas.

In general constants shouldn't be set like this in views because it's not upgrade safe in the case that some other contract tries to save gas by doing this price calculation offchain, even though that may not be as common.

Another reason is just the same as why we store the multiplier, because you might want this to change and so it needs a setter.

Side note: remove unnecessary parentheses

2023-04-13 19:18 UTC, JamesEarle commented on contracts/ZNSPriceOracle.sol
> +    if (length == 0) return 0;
I don't think there is a threat here, it's the equivalent of owning a domain that is `0x0...` and it doesn't have any effect as you wouldn't be able to use it. Plus, in the Registry we declare the owner of `0x0` to be the deployer of that contract and only they'd be able to modify who owns it, so no one can call to register it even if they could get a price here.

2023-04-17 18:06 UTC, merged

2023-04-17 18:09 UTC, zero-devops commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on [GitHub release](https://github.com/zer0-os/zNS/releases/tag/v1.1.0-dev)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: