Adding String Length Check Utility
zer0-os/ZNS pull request #15
Opened 2023-04-20 16:18 UTC by Will-Hyde

Adding a utility that can check the length of strings accurately, an example has been taken from the ENS implementation as it seems to be very well received and reviewed

2023-04-20 16:58 UTC, JamesEarle commented on contracts/ZNSPriceOracle.sol
> +    require(length <= 255, "ZNS: Only names up to 255 characters in length are supported");
A string would be one whole word in storage so 256 bits. It shouldn't be possible to even form the transaction if the string is longer, so this may be redundant because it can never be hit. There is already a `long domain name` test in the oracle here, try increasing the length and seeing if it even creates a transaction for you.

2023-04-20 21:10 UTC, Whytecrowe commented on contracts/ZNSPriceOracle.sol
> +    require(length <= 255, "ZNS: Only names up to 255 characters in length are supported");
good point! was thinking about it as well

2023-04-20 21:11 UTC, Whytecrowe commented on contracts/StringUtils.sol
> +library StringUtils {
let's add 2 empty lines here and put source under the pragma

2023-04-20 21:16 UTC, Whytecrowe commented on contracts/ZNSPriceOracle.sol
> +    uint256 length = StringUtils.strlen(name);
we should change this by adding this line:
`using StringUtils for string;`    right under the contract name, then go:
`name.strlen()` on this line.

This will be a good base if we need to add any other utils in the future. this will also make a `delegatecall` to the library preserving the context and state.
When we outline it like this we are using it as a library rather then contract, which makes txes cheaper.

2023-04-20 21:17 UTC, Whytecrowe commented on contracts/ZNSPriceOracle.sol
>  contract ZNSPriceOracle is IZNSPriceOracle, Initializable {
always two empty lines before `contract` keyword

2023-04-20 21:21 UTC, Whytecrowe requested changes
some minor things in comments

2023-04-20 23:27 UTC, RyanCross approved these changes

2023-04-21 14:09 UTC, JamesEarle commented on contracts/ZNSPriceOracle.sol
> +    require(length <= 255, "ZNS: Only names up to 255 characters in length are supported");
I tested this locally and I was wrong, you can form a tx with a string longer than 256 bits, and it was only failing my tests because I was using `uint8` to hold the length. Weird though is that I swore it was actually failing before it even formed the tx when I went above that length even before reducing the size of the variable.

The question now is should we enforce domain name length? if so, we can keep the vars as `uint8` and then keep this require statement as well, as otherwise it causes overflow for the `uint8`, otherwise we should remove it and set the vars to `uint256` instead.

@Whytecrowe @Will-Hyde ?

2023-04-21 14:10 UTC, JamesEarle commented on contracts/ZNSPriceOracle.sol
> +    require(length <= 255, "ZNS: Only names up to 255 characters in length are supported");
I tested this locally and I was wrong, you can form a tx with a string longer than 256 bits, and it was only failing my tests because I was using `uint8` to hold the length. Weird though is that I swore it was actually failing before it even formed the tx when I went above that length even before reducing the size of the variable.

The question now is should we enforce domain name length? if so, we can keep the vars as `uint8` and then keep this require statement as well, as without it causes overflow for the `uint8` and at 257 chars the domain is free, but at 258 the cost is `basePrice` again. Otherwise we should remove the require statement and set the vars to `uint256` instead.

@Whytecrowe @Will-Hyde ?

2023-04-24 17:02 UTC, Will-Hyde commented on contracts/StringUtils.sol
> +library StringUtils {
Added

2023-04-24 17:03 UTC, Will-Hyde commented on contracts/ZNSPriceOracle.sol
> +    uint256 length = StringUtils.strlen(name);
Updated to call name.strlen()

2023-04-24 17:03 UTC, Will-Hyde commented on contracts/ZNSPriceOracle.sol
>  contract ZNSPriceOracle is IZNSPriceOracle, Initializable {
Added

2023-04-24 21:06 UTC, merged

2023-05-08 22:39 UTC, zero-devops commented
:tada: This PR is included in version 0.3.0 :tada:

The release is available on [GitHub release](https://github.com/zer0-os/zNS/releases/tag/v0.3.0-dev)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: