feat: New ZNS Registry for recording domain data
zer0-os/ZNS pull request #2
Opened 2023-03-21 21:11 UTC by JamesEarle

Registry contract that has records of domainNameHash values as that contain their owning account as well as their resolver.

![image](https://user-images.githubusercontent.com/5976499/226741708-045d43be-b708-4f99-b3df-9af4b93227a6.png)

2023-03-21 22:00 UTC, RyanCross commented on contracts/IRegistry.sol
> +    bytes32 domainNameHash
I think we should consider also emitting the `domainName` string here. Even if we don't explicitly keep it in storage.  We need a permanent record of name -> hash in our ecosystem.

2023-03-21 22:33 UTC, JamesEarle commented on contracts/IRegistry.sol
> +    bytes32 domainNameHash
@RyanCross We will be able to get the human readable name from the DomainToken contract when that's developed. It actually holds the NFT, but this contract only contains the domain name hash which we can't get the domain name from

2023-03-21 23:13 UTC, Whytecrowe commented on contracts/IRegistry.sol
> +interface IRegistry {
let's call it ZNSRegistry so we know which contracts are ours at all times. some of them might be implemented by other parties

2023-03-21 23:14 UTC, Whytecrowe commented on contracts/IRegistry.sol
> +interface IRegistry {
same for other contracts

2023-03-21 23:14 UTC, Whytecrowe commented on contracts/IRegistry.sol
> +    IResolver defaultResolver;
we need to store `address` type here. different Resolvers will have different Interfaces

2023-03-21 23:15 UTC, Whytecrowe commented on contracts/IRegistry.sol
> +    IResolver indexed resolver,
address type here as well

2023-03-21 23:17 UTC, Whytecrowe commented on contracts/IRegistry.sol
> +  function setDomainOperator(address operator, bool allowed) external;
from a recent discussion, having "domain" in the name might be confusing since we do not give it per domain, but rather per owner

2023-03-21 23:17 UTC, Whytecrowe commented on contracts/IRegistry.sol
> +import {IResolver} from "./IResolver.sol";
not needed here

2023-03-21 23:21 UTC, Whytecrowe commented on contracts/Registry.sol
> +  function isAllowedOperator(
we can maybe combine this with "isOwner" concept. so that it checks both in one place and we can use it as a modifier

2023-03-21 23:23 UTC, Whytecrowe commented on contracts/IRegistry.sol
> +    IResolver defaultResolver;
also, why "default" in the name?

2023-03-21 23:25 UTC, Whytecrowe commented on contracts/Registry.sol
> +    return keccak256(abi.encodePacked("znsdomain", domainName));
"znsdomain" should be a constant in the contract that we can get from outside.
also, we might want to move this function to Registrar. please, add a TODO comment so that we can find it easily later.
also, not sure what this does exactly... :)

2023-03-21 23:27 UTC, Whytecrowe commented on contracts/Registry.sol
> +  function _onlyDomainOwnerOrOperator(bytes32 domainNameHash) internal view {
why not make it a modifier?

2023-03-22 15:54 UTC, JamesEarle commented on contracts/Registry.sol
> +  function _onlyDomainOwnerOrOperator(bytes32 domainNameHash) internal view {
We used internal functions before instead of modifiers because they are more optimal in situations where you're constrained by contract size ([source](https://0xmacro.com/blog/solidity-gas-optimizations-cheat-sheet/)), as we were with the original registrar contract. I suppose it became a habit, but I will change to use a modifier instead.

2023-03-22 16:58 UTC, JamesEarle commented on contracts/IRegistry.sol
> +  function setDomainOperator(address operator, bool allowed) external;
Makes sense, but also the operator permissions are specific to domains of the owner, not the owner themselves. I'll change it but that's the thought I have

2023-03-22 17:03 UTC, JamesEarle commented on contracts/Registry.sol
> +  function isAllowedOperator(
What you're describing is already done in the `onlyOwnerOrOperator` modifier (that was an internal function before)

2023-03-22 17:05 UTC, JamesEarle commented on contracts/Registry.sol
> +    return keccak256(abi.encodePacked("znsdomain", domainName));
This is what we discussed yesterday, a simple view function to return the hashed domain name if it's needed by say the DomainToken contract, where names are kept in their human readable form

2023-03-22 20:52 UTC, Whytecrowe commented on contracts/Registry.sol
> +    return keccak256(abi.encodePacked("znsdomain", domainName));
DomainToken will probably NOT keep the names in human readable form. for now I see only Registrar being able to do that. even then, it will not keep them, but can help users hash from a string label. after it gets in the system past Registrar, contracts only view domains as hashes, so that they are the same across contracts.

Why do we encode with "znsdomain" string? what about the parent domain hash?
Shouldn't it be `hash(encode(hash("parentName"), stringLabel))` ?

2023-03-22 20:55 UTC, Whytecrowe commented on contracts/Registry.sol
> +  function _onlyDomainOwnerOrOperator(bytes32 domainNameHash) internal view {
makes sense. although, modifiers are a good and convenient convention to have. imo, we should really only remove them when we are very tight on the bytecode size.

2023-03-23 15:50 UTC, JamesEarle commented on contracts/Registry.sol
> +    return keccak256(abi.encodePacked("znsdomain", domainName));
We don't keep a child domain -> parent domain pointer, so the parent domain would have to be a param to this func. If you think it's possible we won't keep this here at all, maybe we should just remove it?

2023-03-24 15:49 UTC, beardhero commented on contracts/Registry.sol
> +    return keccak256(abi.encodePacked("znsdomain", domainName));
Following what ens does, this "znsdomain" value should be the namehash of the TLD. eg namehash("wilder.")

2023-03-24 15:57 UTC, beardhero commented on contracts/Registry.sol
> +    string memory domainName
This domainName param should not be the human-readable name. It should be the namehash of the human-readable name.
This is so that we can handle a name at any depth, without any need for pointers from child -> parent

2023-03-24 16:59 UTC, JamesEarle commented on contracts/Registry.sol
> +    string memory domainName
The function is to get the `domainNameHash` value of the domain name. If we expect that in the parameter, we assume the user already has that value which would render this useless anyways.

In talks with Kirill we're not sure about where a function like this will end up, but it's more likely going to be the ZNSRegistrar when that is made, maybe. We're not sure but it will be finalized before deployment.

2023-03-24 19:37 UTC, Whytecrowe commented on contracts/IZNSRegistry.sol
> +import {IZNSResolver} from "./IZNSResolver.sol";
don't think we need this here

2023-03-24 19:39 UTC, Whytecrowe commented on contracts/ZNSRegistry.sol
> +  // What/where should this be?
for comments like these, could you please add TODO in the beginning. many IDEs make it very easy to look for them when doing final software review and make them a different color. otherwise we might forget about them

2023-03-24 19:46 UTC, Whytecrowe commented on contracts/ZNSRegistry.sol
> +    require(!_exists(domainNameHash), "ZNS: Domain exists");
is there a way to optimize this along with the `validDomain` modifier? the difference seems to be only the "NOT" for `_exists` function. so that the solution can be used accross the contract in the same-ish way.

2023-03-24 19:49 UTC, Whytecrowe commented on contracts/ZNSRegistry.sol
> +    require(currentResolver != resolver, "ZNS: Same resolver");
these 2 lines above are not needed. extra gas for no reason, really.

2023-03-24 19:50 UTC, Whytecrowe commented on contracts/ZNSRegistry.sol
> +   * to enable burning them instead by transferring ownership to `address(0)`
good comment!

2023-03-24 19:51 UTC, Whytecrowe commented on hardhat.config.ts
> +require("@nomicfoundation/hardhat-chai-matchers");
why `require` here instead of `import`?

2023-03-24 19:53 UTC, Whytecrowe commented on src/deploy.ts
> +import { Registry, Registry__factory } from "../typechain";
is this an older typechain object? since the contract name has changed

2023-03-24 19:56 UTC, Whytecrowe commented on src/deploy.ts
> +  console.log(gasB);
nice! in the future we want to create a gas test "stencil" so that we can track all the gas changes every time we change SC code and also test different ways of implementing solutions.
we will eventually be charging users a decent amount, so, ideally, we want to make transactions cheaper anywhere we can, so that it doesn't seem too expensive to use our platform.

2023-03-24 19:59 UTC, Whytecrowe commented on test/registry.test.ts
> +  //  a valid operator can change the owner of a domain, is this wanted?
good question. let's add this to the spec.

2023-03-24 20:00 UTC, Whytecrowe commented on test/registry.test.ts
> +    it("Returns true when an operator is allowed by an owner", async () => {
let's add empty lines between cases for better readability

2023-03-24 20:15 UTC, Whytecrowe commented on test/registry.test.ts
> +      await registry.connect(deployer).createDomainRecord(wilderDomainHash, mockResolver.address);
interesting case... Maybe we shouldn't allow to set a record without an owner. this may need to revert if owner is not specified.
thoughts?

2023-03-24 20:17 UTC, Whytecrowe commented on test/registry.test.ts
> +    it("Allows setting domain record owner as the 0 address", async () => {
another test for the same case.
good idea for adding this one!
let's try and figure out if we want it to be this way. what are the possible situations where this might be beneficial and what are the ones where we do not want this to happen?

remember that we also check the existence of the domain through the `owner` field. in this case our checks will show that a domain does not exist, but it will exist with the possible resolver set.

2023-03-24 20:20 UTC, Whytecrowe commented on contracts/ZNSRegistry.sol
> +    );
another seemingly unnecessary check.

2023-03-24 20:21 UTC, Whytecrowe commented on test/registry.test.ts
> +      await registry.connect(operator).setDomainResolver(wilderDomainHash, operator.address);
why do we have both of these functions present (create... and set...) on the contact? they seem to be doing the same thing. I think, one should be enough.

2023-03-24 20:22 UTC, Whytecrowe commented on test/registry.test.ts
> +      const tx = registry.connect(deployer).setDomainRecord(wilderDomainHash, operator.address, hre.ethers.constants.AddressZero);
so, we are allowing to set `owner` as 0, but not `resolver`. why?
same situation as the above comment.

2023-03-24 20:23 UTC, Whytecrowe commented on test/registry.test.ts
> +    });
don't think we need this check at all, as said in one of the comments above. why is this beneficial, you think?

2023-03-24 20:24 UTC, Whytecrowe commented on test/registry.test.ts
> +    });
same here

2023-03-24 20:25 UTC, Whytecrowe commented on test/registry.test.ts
> +      // We have not called to create the domain record, so it won't exist
or we have a domain record set with 0 as owner and a valid resolver address...

2023-03-24 20:29 UTC, Whytecrowe requested changes
Amazing start!
Let's discuss the comments and iron out the things left.

2023-03-24 22:04 UTC, JamesEarle commented on hardhat.config.ts
> +require("@nomicfoundation/hardhat-chai-matchers");
Just forgot to change back to the above commented import. I was having trouble getting this working right at first and wanted to make sure I was following the docs exactly

2023-03-24 22:08 UTC, JamesEarle commented on src/deploy.ts
> +import { Registry, Registry__factory } from "../typechain";
updated

2023-03-24 22:21 UTC, JamesEarle commented on test/registry.test.ts
> +      await registry.connect(operator).setDomainResolver(wilderDomainHash, operator.address);
the `onlyOwnerOrOperator` modifier restricts other functions to only be executable by an owner or an operator, but to create a new domain it's not possible there is an owner yet because it is new. So the second function.

2023-03-24 22:22 UTC, JamesEarle commented on test/registry.test.ts
> +      const tx = registry.connect(deployer).setDomainRecord(wilderDomainHash, operator.address, hre.ethers.constants.AddressZero);
setting owner as 0 burns the domain, but setting resolver to 0 for a valid domain would just break it, presumably. Do you disagree?

2023-03-24 22:24 UTC, JamesEarle commented on test/registry.test.ts
> +    });
It would be a wasted, unnecessary tx if you were to submit `setDomainOwner` with the value of the current owner, even if very unlikely. So this is to avoid allowing users to make that mistake

2023-03-24 23:01 UTC, JamesEarle commented on test/registry.test.ts
> +      // We have not called to create the domain record, so it won't exist
@Whytecrowe I don't understand what you mean here. If changing `owner` to `0` on a domain is burning it in the system, how can it be considered here?

2023-03-30 17:56 UTC, Whytecrowe approved these changes

2023-03-30 17:56 UTC, merged

2023-04-04 04:30 UTC, zero-devops commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/zer0-os/zNS/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-04-05 01:06 UTC, zero-devops commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/zer0-os/zNS/releases/tag/dev-v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-04-07 23:08 UTC, zero-devops commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/zer0-os/zNS/releases/tag/v1.0.0-dev)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: