Feat/mud 222 reclaim logic
zer0-os/ZNS pull request #20
Opened 2023-05-04 19:50 UTC by Will-Hyde

Adding logic and tests for reclaim functionality

2023-05-04 20:08 UTC, Whytecrowe commented on contracts/distribution/ZNSEthRegistrar.sol
> +    require(znsDomainToken.isOwner(tokenId, msg.sender), "ZNSEthRegistrar: Not owner of domain");
imo, this should be the first check.
Also, in the message, I think, more clear would be to say "Not a token owner" rather than "domain". the caller is technically only trying to be the full domain owner at this point

2023-05-04 20:09 UTC, Whytecrowe commented on contracts/distribution/ZNSEthRegistrar.sol
> +    require(owner != msg.sender, "ZNSEthRegistrar: Caller already owner of domain registry");
"Domain is already owned by the caller"

2023-05-04 20:12 UTC, Whytecrowe commented on contracts/distribution/ZNSEthRegistrar.sol
> +    znsAddressResolver.setAddress(domainHash, msg.sender);
this is not the best assumption here. a person can own a domain, but assign it to a contract or something else.
this should either not be included at all or we need to provide another parameter to this function to specifically set resolver to a certain address. in this case there should also be an option to provide zero address, if zero address is provided, then we do not set anything on the resolver. they can set it later at their own time.

look here for reference of what I mean - https://github.com/zer0-os/zNS/blob/feat/ZNSRegistrar/contracts/distribution/ZNSEthRegistrar.sol#L225-L246

2023-05-04 20:18 UTC, Whytecrowe commented on contracts/token/ZNSDomainToken.sol
> +  function isOwner(
is this function necessary?
can't we just do:
`require(znsDomainToken.ownerOf(tokenId) == msg.sender)`  in the contract where we need to check?

2023-05-04 20:19 UTC, Whytecrowe commented on test/ZNSEthRegistrar.test.ts
> +      // Verify domain is owned in registrar
"in registry"

2023-05-04 20:21 UTC, Whytecrowe commented on test/ZNSEthRegistrar.test.ts
> +      await zns.domainToken.connect(deployer).transferFrom(deployer.address, user.address, tokenId);
this doesn't have to be `transferFrom()` can just be `transfer()` when the owner of the token transfers himself. this way we do not need an extra `approve()` transaction.
`transferFrom()` is used when somebody else transfers your token

2023-05-04 20:23 UTC, Whytecrowe commented on test/ZNSEthRegistrar.test.ts
> +  });
need another test where domain is tranferred, reclaimed and the revoked to make sure the new owner can unstake. check balances in this one to make sure all transfers happened properly

2023-05-05 03:56 UTC, Will-Hyde commented on contracts/distribution/ZNSEthRegistrar.sol
> +    require(znsDomainToken.isOwner(tokenId, msg.sender), "ZNSEthRegistrar: Not owner of domain");
Ok, I moved this check  up and changed the require statement

2023-05-05 03:57 UTC, Will-Hyde commented on contracts/distribution/ZNSEthRegistrar.sol
> +    require(owner != msg.sender, "ZNSEthRegistrar: Caller already owner of domain registry");
Modified

2023-05-05 04:01 UTC, Will-Hyde commented on contracts/distribution/ZNSEthRegistrar.sol
> +    znsAddressResolver.setAddress(domainHash, msg.sender);
I guess im confused here, are you saying I should or shouldnt set the address on the resolver? Or are you saying I shouldnt unless I can verify its not a contract address?

2023-05-05 04:05 UTC, Will-Hyde commented on contracts/distribution/ZNSEthRegistrar.sol
> +    require(znsDomainToken.isOwner(tokenId, msg.sender), "ZNSEthRegistrar: Not owner of domain");
Actually, on second thought:
If I move this statement up, then the error message that bubbles up is "ERC721: Invalid Token ID" which means that I should either keep it where it is or remove the earlier line entirely (Otherwise it serves no purpose because it will never trigger)

2023-05-05 04:08 UTC, Will-Hyde commented on contracts/token/ZNSDomainToken.sol
> +  function isOwner(
ownerOf is not exposed by the DomainToken Interface and is instead on the ERC721 interface.

So if I wanted to call that here, I would need to make DomainToken implement some function that calls ownerOf on the token in some way, I just thought this was a simple way to expose what we needed

2023-05-05 04:08 UTC, Will-Hyde commented on test/ZNSEthRegistrar.test.ts
> +      // Verify domain is owned in registrar
fixed

2023-05-05 04:14 UTC, Will-Hyde commented on test/ZNSEthRegistrar.test.ts
> +      await zns.domainToken.connect(deployer).transferFrom(deployer.address, user.address, tokenId);
As far as I can tell the Transfer method has 3 optional arguments, (from to and tokenID). Which are all the same arguments, also, it doesnt appear that transfer is exposed publicly by ERC721 and is instead an internal method, I could write a wrapper for it and expose it though. Is that what I should do?

2023-05-05 20:16 UTC, Will-Hyde commented on test/ZNSEthRegistrar.test.ts
> +  });
Added

2023-05-08 19:33 UTC, Whytecrowe commented on contracts/distribution/ZNSEthRegistrar.sol
> +    znsAddressResolver.setAddress(domainHash, msg.sender);
I guess, I'm saying to think on this a bit more.

Since we are planning multiple resolvers of different types, we can't future proof the function arguments type-wise. We either taking an address to the domain content and assume they will bind it to an address OR we not take any args related to the domain content, leaving the user to set it themselves at a different time on Resolver directly. Another option here is to offer a default way of setting an address only, if a user wishes to do so, but there should be an option for him to not provide it. In case he wants to tie it to the bytes32 data or a string or anything else, and not address. When he provides 0, we assume he wants to do that himself at another time and do not set anything.

Does it make sense?

2023-05-08 19:36 UTC, Whytecrowe commented on contracts/token/ZNSDomainToken.sol
> +  function isOwner(
well, this is a bigger problem then, if I understand this correctly. we want our DomainToken to be fully ERC-721 compatible. if we can't access basic 721 functions, this is not an NFT token. we should inherit the ERC-721 interface by ZNSDomainToken interface and then this interface is inherited by ZNSDomainToken impl contract. this way we will catch all the missing functions. if a certain function is not exposed in the ERC-721 base contract, we need to expose it in the ZNSDomainToken.
I see that IERC721 is NOT inherited by the IZNSDomainToken. which is not good. we should definitely do that and then expose or add functions we are missing

2023-05-08 19:54 UTC, Whytecrowe commented on test/ZNSEthRegistrar.test.ts
> +      await zns.domainToken.connect(deployer).transferFrom(deployer.address, user.address, tokenId);
my bad, incorrectly assumed this was erc20 for some unknown reason.
you are right. let's use `safeTransferFrom()` then. look into `onERC721Received` specifications.
this might not be necessary, but we need to be sure. this is partially to cover some old contracts that did incorrect returns  and some other things, like adding some confidence that a receiving contract can handle the transferred tokens.
Let me know what you think on this. Should we implement it or not?

2023-05-08 19:55 UTC, Whytecrowe requested changes
After all the changes are done, please, update the branch from `development`.
Make sure that Registrar PR has been merged at that point before you update.

2023-05-08 20:18 UTC, Whytecrowe commented on contracts/distribution/ZNSEthRegistrar.sol
> +    require(znsDomainToken.isOwner(tokenId, msg.sender), "ZNSEthRegistrar: Not owner of domain");
I guess this error is fired by the `ownerOf()` when we are passing an ID of token that doesn't exist. which is totally fine, right?
we are checking an owner here for tokens that do exist. check if you have a test for that specifically.
if we have a token and somebody other than it's owner is trying to access this function, it should fail in that require.
Am I assuming correctly here?

2023-05-08 22:40 UTC, Whytecrowe commented on test/ZNSEthRegistrar.test.ts
> +      await zns.domainToken.connect(deployer).transferFrom(deployer.address, user.address, tokenId);
we technically do not transfer this token to any of our contracts. so if we do implement this, whatever contract receives it at any point, has to have `onERC721Received` implemented. so we may not need it, however safeTransfer is usually a better approach.

2023-05-09 05:02 UTC, Will-Hyde commented on contracts/distribution/ZNSEthRegistrar.sol
> +    require(znsDomainToken.isOwner(tokenId, msg.sender), "ZNSEthRegistrar: Not owner of domain");
Yes thats right, thats what its checking. And yes I have a test case that covers if someone tries to reclaim the domain without owning the token. I think this code should stay the same

2023-05-09 05:06 UTC, Will-Hyde commented on contracts/distribution/ZNSEthRegistrar.sol
> +    znsAddressResolver.setAddress(domainHash, msg.sender);
I dont think it makes sense to me, im not sure what this has to do with the current story. Are you asking me to make a change here or no? If were going to change how resolvers work, should I just leave this in and have us update it later?

2023-05-09 05:07 UTC, Will-Hyde commented on contracts/token/ZNSDomainToken.sol
> +  function isOwner(
Ok I can have the DomainToken interface inherit from IERC-721 and that should  expose it

2023-05-09 05:12 UTC, Will-Hyde commented on test/ZNSEthRegistrar.test.ts
> +      await zns.domainToken.connect(deployer).transferFrom(deployer.address, user.address, tokenId);
![image](https://user-images.githubusercontent.com/25021249/236999700-83673ae9-7b61-4a1f-a0f3-17ffdca37943.png)

Yes if the receiver address is a contract, it needs to inherit onERC721Received

2023-05-09 17:21 UTC, Whytecrowe commented on contracts/distribution/ZNSEthRegistrar.sol
> +    znsRegistry.setSubdomainOwner(domainHash, domainHash, msg.sender);
why are parent and child the same domain here? this is an interesting case...
parentHash is used in `setSubdomainOwner` to check the access. here you are tricking it to check the access of the current domain. this this raise questions for you when you wrote it? is it fine that Registry access checks can be circumvented?

2023-05-09 17:22 UTC, Will-Hyde commented on contracts/distribution/ZNSEthRegistrar.sol
> +    znsAddressResolver.setAddress(domainHash, msg.sender);
Removing the call to the addressResolver

2023-05-09 17:22 UTC, Whytecrowe commented on test/ZNSEthRegistrar.test.ts
> +      await zns.registrar.connect(user).reclaimDomain(domainHash);
before doing this, let's check who the original owner is of this domain in Registry to validate.

2023-05-09 17:25 UTC, Will-Hyde commented on contracts/distribution/ZNSEthRegistrar.sol
> +    znsRegistry.setSubdomainOwner(domainHash, domainHash, msg.sender);
The "parent" in this case (in the setSubdomainOwner function) is only being used to determine who owns the domain. In this case, im using the child for both because I only care if the message sender is the owner of the domain in question

2023-05-09 17:26 UTC, Whytecrowe commented on contracts/distribution/ZNSEthRegistrar.sol
> +  function reclaimDomain(bytes32 domainHash) external {
should we take `tokenId` as an argument here? a person who received the token might not know what the domain is or it's hash, but he should know `tokenId` of the token he owns. what do you think?

2023-05-09 17:29 UTC, Will-Hyde commented on contracts/distribution/ZNSEthRegistrar.sol
> +  function reclaimDomain(bytes32 domainHash) external {
I think I made it domainHash, because revokeDomain also takes domainHash (and also all the other functions in this contract)

Personally, I would want to keep the methods similar. It seems the rest are all using domainHash right now

2023-05-09 17:29 UTC, Will-Hyde commented on test/ZNSEthRegistrar.test.ts
> +      await zns.registrar.connect(user).reclaimDomain(domainHash);
Ok, I have added this check

2023-05-09 17:30 UTC, Whytecrowe commented on contracts/distribution/ZNSEthRegistrar.sol
> +    znsRegistry.setSubdomainOwner(domainHash, domainHash, msg.sender);
sorry, edited the comment above

2023-05-09 17:35 UTC, Will-Hyde commented on contracts/distribution/ZNSEthRegistrar.sol
> +    znsRegistry.setSubdomainOwner(domainHash, domainHash, msg.sender);
Yes, I think its a security issue. Because this method is exposed externally, and that means any caller can call it to set the owner of any other domain (by passing it their own domain as parent to prove ownership).

I also think this method does not relate to my story, and this function should be addressed in the story that sets appropriate access control

2023-05-09 17:36 UTC, Whytecrowe commented on contracts/distribution/ZNSEthRegistrar.sol
> +    znsRegistry.setSubdomainOwner(domainHash, domainHash, msg.sender);
I think the main issue is our Registry functions... we need a better access checks there for owners.
The only reason this call passes is because in tests Registrar is set to be the operator of all `user` domains.
in reality, it will not be, so it will always fail.

2023-05-09 17:36 UTC, Will-Hyde commented on contracts/distribution/ZNSEthRegistrar.sol
> +    znsRegistry.setSubdomainOwner(domainHash, domainHash, msg.sender);
Ill add a todo, to make sure this gets addressed when AccessControl is implemented

2023-05-09 17:43 UTC, Whytecrowe commented on contracts/distribution/ZNSEthRegistrar.sol
> +    znsRegistry.setSubdomainOwner(domainHash, domainHash, msg.sender);
the parent hash in this case should be ROOT_HASH which Registrar actually owns/operates by default. the current call will not work in real world, because we can't own or operate on users' domains. we only own and operate the root (0://).

2023-05-09 17:46 UTC, Whytecrowe commented on contracts/distribution/ZNSEthRegistrar.sol
> +  function reclaimDomain(bytes32 domainHash) external {
ok. they are technically interchangeable.

2023-05-09 17:47 UTC, Whytecrowe commented on test/ZNSEthRegistrar.test.ts
> +    it ("Revokes a SubDomain - Happy Path", async () => {
why whitespaces here? they are not on any other tests.

2023-05-09 17:47 UTC, Will-Hyde commented on contracts/distribution/ZNSEthRegistrar.sol
> +    znsRegistry.setSubdomainOwner(domainHash, domainHash, msg.sender);
Ok sure, Ill update the parenthash to be the root hash

2023-05-09 17:49 UTC, Will-Hyde commented on test/ZNSEthRegistrar.test.ts
> +    it ("Revokes a SubDomain - Happy Path", async () => {
Not sure, when I merged it added them. I removed them now

2023-05-09 19:03 UTC, merged

2023-05-19 22:24 UTC, zero-devops commented
:tada: This PR is included in version 0.3.1 :tada:

The release is available on [GitHub release](https://github.com/zer0-os/zNS/releases/tag/v0.3.1-dev)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: