fix: Making ZNSDomainToken Upgradeable
zer0-os/ZNS pull request #22
Opened 2023-05-12 18:42 UTC by Will-Hyde

Adding the Upgradeable ERC721 interface to the domain token, so that it can make use of Open Zeppelin's Transparent Proxy

2023-05-15 16:20 UTC, JamesEarle approved these changes

2023-05-15 23:39 UTC, RyanCross commented
@Whytecrowe @Will-Hyde What do y'all think about making this proxy UUPS (inheriting from https://docs.openzeppelin.com/contracts/4.x/api/proxy#UUPSUpgradeable)

OpenZeppelin's latest recommendation on proxies appears to have shifted over time to this pattern.  Which moves upgrade logic to the implementation contract and not the proxy contract.

Further reading:
https://docs.openzeppelin.com/contracts/4.x/api/proxy#transparent-vs-uups

2023-05-19 23:02 UTC, Whytecrowe commented
> @Whytecrowe @Will-Hyde What do y'all think about making this proxy UUPS (inheriting from https://docs.openzeppelin.com/contracts/4.x/api/proxy#UUPSUpgradeable)
> 
> OpenZeppelin's latest recommendation on proxies appears to have shifted over time to this pattern. Which moves upgrade logic to the implementation contract and not the proxy contract.
> 
> Further reading: https://docs.openzeppelin.com/contracts/4.x/api/proxy#transparent-vs-uups

Could you, please, look into it @JamesEarle ? Maybe UUPS would be better here?

2023-05-25 19:13 UTC, Whytecrowe commented on contracts/token/ZNSDomainToken.sol
> +     * @dev Using solhint's `no-empty-blocks` will error here, but to be a UUPS Proxy we require it this
looks like an outdated comment

2023-05-25 19:19 UTC, Whytecrowe commented on package.json
> +    "lint": "yarn lint-sol & yarn lint-ts",
you want these to run in parallel?

2023-05-25 19:20 UTC, Whytecrowe commented on test/ZNSDomainToken.test.ts
> -      expect(await domainToken.ownerOf(tokenId)).to.equal(caller.address);
why is this removed? we need to verify that the token was, in fact, transferred to the correct address. an event does not verify this

2023-05-25 19:25 UTC, Whytecrowe commented on test/ZNSDomainToken.test.ts
> -      await expect(
same here

2023-05-25 19:26 UTC, Whytecrowe commented on test/ZNSDomainToken.test.ts
> +        `AccessControl: account ${caller.address.toLowerCase()} is missing role ${REGISTRAR_ROLE}`
there's a helper for this:
https://github.com/zer0-os/zNS/blob/development/test/helpers/errors.ts#L1

2023-05-25 19:27 UTC, Whytecrowe commented on test/ZNSDomainToken.test.ts
> +    it("Allows setting of a new access controller if the caller is a governor", async () => {
admin, not governor

2023-05-25 19:28 UTC, Whytecrowe commented on test/ZNSDomainToken.test.ts
> +        `AccessControl: account ${caller.address.toLowerCase()} is missing role ${GOVERNOR_ROLE}`
use helper

2023-05-25 19:28 UTC, Whytecrowe commented on test/ZNSDomainToken.test.ts
> +    it("Allows setting of a new access controller if the caller is a governor", async () => {
also, the newly merged AC PR has all these tests. please, verify and remove redundant ones

2023-05-25 19:29 UTC, Whytecrowe commented on test/ZNSDomainToken.test.ts
> +  describe("UUPS", () => {
space before this

2023-05-25 19:30 UTC, Whytecrowe commented on test/ZNSDomainToken.test.ts
> +      await expect(zns.accessController.checkRole(GOVERNOR_ROLE, deployer.address)).to.not.be.reverted;
use `hasRole()` or `isGovernor()` instead here. they return a boolean.

2023-05-25 19:31 UTC, Whytecrowe commented on test/ZNSDomainToken.test.ts
> +        `AccessControl: account ${caller.address.toLowerCase()} is missing role ${GOVERNOR_ROLE}`
helper

2023-05-25 19:32 UTC, Whytecrowe commented on test/ZNSDomainToken.test.ts
> +      expect(symbolBefore).to.eq(symbolAfter);
what about the state vars that actually matter? :) like token ownership and stuff...
what about the new functionality? is it added with the upgrade? are new slots added with the upgrade? do they interfere with old slots?

2023-05-25 19:33 UTC, Whytecrowe commented on test/ZNSDomainToken.test.ts
> +      expect(symbolBefore).to.eq(symbolAfter);
a helper can be potentially created here that can be reused for tests of other proxies.

2023-05-25 19:34 UTC, Whytecrowe commented on test/ZNSDomainToken.test.ts
> +      const factory = new ZNSDomainToken__factory(deployer);
need to upgrade to a contract with slightly different logic (new function(-s), new storage slots) to actually verify. upgrading to the identical logic doesn't really check much

2023-05-25 19:35 UTC, Whytecrowe commented on test/ZNSDomainToken.test.ts
> +      const factory = new ZNSDomainToken__factory(deployer);
for the AC failed call, this is fine

2023-05-25 19:36 UTC, Whytecrowe commented on test/helpers/deployZNS.ts
> +      "ZNSDomainToken",
these should be constants, especially if we check them in multiple tests and use them in helpers

2023-05-25 19:38 UTC, Whytecrowe commented on test/helpers/deployZNS.ts
> +  // TODO AC: Make sure contracts are deployed as proxies and authorize the governor role
not sure what this comment means

2023-05-25 19:38 UTC, Whytecrowe requested changes
please address the comments + resolver conflicts

2023-05-28 19:54 UTC, JamesEarle commented on package.json
> +    "lint": "yarn lint-sol & yarn lint-ts",
I was getting different output if I ran in parallel vs consecutively, so I left it.

2023-05-28 19:58 UTC, JamesEarle commented on test/ZNSDomainToken.test.ts
> -      expect(await domainToken.ownerOf(tokenId)).to.equal(caller.address);
Meant to put this back, it's added

2023-05-28 20:01 UTC, JamesEarle commented on test/ZNSDomainToken.test.ts
> +        `AccessControl: account ${caller.address.toLowerCase()} is missing role ${REGISTRAR_ROLE}`
changed all of them to this, thanks

2023-05-28 20:10 UTC, JamesEarle commented on test/helpers/deployZNS.ts
> +  // TODO AC: Make sure contracts are deployed as proxies and authorize the governor role
a lot clearer than comments like "fix this!" to me, but this was because some contracts were being deployed through their factory still not through the `upgrades.deployProxy()` command like others, but this has been changed

2023-06-05 19:06 UTC, merged

2023-06-05 19:13 UTC, zero-devops commented
:tada: This PR is included in version 0.5.0 :tada:

The release is available on [GitHub release](https://github.com/zer0-os/zNS/releases/tag/v0.5.0-dev)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: