Address resolver
zer0-os/ZNS pull request #6
Opened 2023-03-31 16:42 UTC by beardhero

No upgradeability.

Branched from feat/namehash.

2023-03-31 17:13 UTC, JamesEarle commented
Please merge latest on master and resolve the existing conflicts.

Also in the future please add reviewers so that we get notifcations when you make a PR.

2023-03-31 17:20 UTC, JamesEarle commented on contracts/ZNSRegistry.sol
> +  function createSubDomainRecord(string memory label, bytes32 parentHash, address resolver) public {
Why is this function here? This looks repetitive, and also isn't used in your work creating the address resolver? The `setSubdomainRecord` function would cover this, with the small added detail of using an `address owner` param instead of `msg.sender`

2023-03-31 17:22 UTC, JamesEarle commented on yarn-error.log
Please remove this file from the commit

2023-03-31 17:23 UTC, JamesEarle commented on contracts/ZNSAddressResolver.sol
Be sure to run the formatter on everything

2023-03-31 17:26 UTC, JamesEarle commented on contracts/ZNSAddressResolver.sol
> +    bytes4 internal constant RESOLVER_INTERFACE_ID = 0xe25f0a33;
Please always add comments for numbers like this. Where did it come from? What does it do? Why do we need it?

2023-03-31 17:30 UTC, JamesEarle commented on contracts/ZNSAddressResolver.sol
> +    function supportsInterface(bytes4 interfaceId)external view returns (bool){
Can you explain what this is for? And the above pre-calculated interface ID?


Can be made `pure`, also please use natspec formatting like above for comments.

2023-03-31 17:37 UTC, JamesEarle commented on contracts/IZNSAddressResolver.sol
Dev tip: There is already a `.prettierrc` in the repo, enable "format on save" for consistency with other code in repo automatically

2023-03-31 18:29 UTC, JamesEarle commented on contracts/ZNSAddressResolver.sol
> +        addressOf[domainNameHash] = newAddress;
Do we allow setting to `address(0)`?

2023-03-31 18:30 UTC, JamesEarle commented on contracts/ZNSAddressResolver.sol
> +    mapping(bytes32 => address) public addressOf;
Additionally just add a comment for each state variable too. It can be one line and short, but it should just quickly explain what it logically represents and how it's used

2023-03-31 18:35 UTC, JamesEarle commented on test/namehash.test.ts
> +  it("Should normalize the name", async function () {
Looks like this is just testing ethers functionality, and I think we should only be testing our own created functionality, not a public and released 3rd party package. They already would (read: should) have much more thorough testing anyways.

IMO this file can be removed

2023-03-31 18:38 UTC, JamesEarle commented on test/registry.test.ts
> +      await registry.connect(deployer).createSubDomainRecord(label, wilderDomainHash, mockResolver.address);
Please pull latest from master and merge. This function should be the `setSubdomainRecord` function and these scenarios are already tested

2023-03-31 18:44 UTC, JamesEarle commented on contracts/ZNSAddressResolver.sol
> +    function setAddress(bytes32 domainNameHash, address newAddress) external onlyRegistry{
Have we confirmed that this is for sure `onlyRegistry`?

Does a request for the resolution of a token to it's mapped address always come from the Registrar? Does the DomainToken contract ever request it? And if so, does it request it directly? Or does it request it from the Registrar, which then requests it from the resolver?

2023-04-03 16:22 UTC, beardhero commented on contracts/ZNSAddressResolver.sol
> +        addressOf[domainNameHash] = newAddress;
Unspecified, as of now this contract has no reason to restrict any use, the permitted setter can restrict appropriately.

2023-04-03 18:32 UTC, Whytecrowe commented on contracts/ZNSAddressResolver.sol
> +  bytes4 internal constant RESOLVER_INTERFACE_ID = 0xe25f0a33; /// @notice pre-calculated erc-165 interface ID
let's make it hash at compile time. this way we have visibility on what that interface is exactly. here I am not sure, nor will other devs be

2023-04-03 18:34 UTC, Whytecrowe commented on contracts/ZNSAddressResolver.sol
> +  mapping(bytes32 => address) public addressOf; /// @notice mapping of domain hash to owning address
if we have a specific getter, let's make this private.

2023-04-03 18:38 UTC, Whytecrowe commented on contracts/ZNSAddressResolver.sol
> +  ) external onlyRegistry {
instead of guarding it for Registry only, it should be done for an authorized user. domain owners or their authorized parties should be able to re-set this at any time. Registry will only do this once upon registering, but the owner might want to change it to another address at any point.

2023-04-03 18:41 UTC, Whytecrowe commented on test/ZNSAddressResolver.test.ts
> +        const supported = await znsAddressResolver.supportsInterface("0xe25f0a33");
again here. what is this hash value? where do we get it from? how do we know if this test is right if we have no idea what we are hashing? :)

2023-04-03 18:41 UTC, Whytecrowe commented on test/ZNSAddressResolver.test.ts
> +});
missing events tests.

2023-04-03 18:43 UTC, Whytecrowe approved these changes
please, address comments, merge `master` into this branch and possibly remove the changes from `feat/namehash`. that branch was not merged and doesn't seem to have necessary code for this PR.
do not branch from `feat/namehash` in the future.

2023-04-03 18:43 UTC, Whytecrowe requested changes
see the message above

2023-04-04 16:57 UTC, RyanCross commented on contracts/ZNSAddressResolver.sol
> +  ) external onlyRegistry {
Consider extending `AccessControlUpgradeable` to accomplish the above.    

@Whytecrowe @beardhero As far as roles themselves. Are there any design requirements for this yet?  Where in the system does one become an authorized party? 

I believe AccessControl comes with a built-in-defined ADMIN which could be defaulted to the owner, but we can additionally define more roles.

2023-04-05 17:42 UTC, JamesEarle commented on contracts/ZNSAddressResolver.sol
> +  ) external onlyRegistry {
@RyanCross might be a good idea, but I would say only add this if we need more than one role. If we only need authorized vs. not authorized, it would be excessive.

2023-04-05 17:49 UTC, JamesEarle commented on contracts/IZNSDomainToken.sol
Any idea why it shows an entire deletion and addition for each file like this? Kind of interferes reviewing the real changes

2023-04-05 18:12 UTC, JamesEarle commented on contracts/IZNSResolver.sol
This file should be deleted if we renamed to `IZNSAddressResolver` and the interface for that file exists now

2023-04-05 23:36 UTC, beardhero commented on test/ZNSAddressResolver.test.ts
> +});
the event was already tested during the setAddress test

2023-04-06 16:04 UTC, beardhero commented on contracts/ZNSAddressResolver.sol
> +  bytes4 internal constant RESOLVER_INTERFACE_ID = 0xe25f0a33; /// @notice pre-calculated erc-165 interface ID
calculateSelector() check added

2023-04-06 16:06 UTC, beardhero commented on contracts/ZNSAddressResolver.sol
> +  ) external onlyRegistry {
I added a modifier onlyOwnerOrOperator to the resolver.
It had to do two checks getDomainRecord and isAllowedOperator.
Consider adding a single check on the registry for onlyOwnerOrOperator.

2023-04-06 16:08 UTC, beardhero commented on contracts/IZNSDomainToken.sol
Whoops! Real sorry about that.
It was due to my dev setup and is resolved for the future now, but this PR is still messy.

2023-04-10 14:28 UTC, JamesEarle commented
If the other one that I see in PRs view is meant to replace this now, please mark this closed

2023-04-10 23:04 UTC, closed without merging